/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.GUI;

import com.vektorel.Util.StaticValues;
import javax.swing.JOptionPane;
import javax.swing.text.Caret;

/**
 *
 * @author vektorel
 */
public class frmLogin extends javax.swing.JFrame {

    private boolean durum = false;
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        lblcancelline.setVisible(false);
        lblsinginline.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        pnlcancel = new javax.swing.JPanel();
        lblcancel = new javax.swing.JLabel();
        lblcancelline = new javax.swing.JLabel();
        pnlsignin = new javax.swing.JPanel();
        lblsignin = new javax.swing.JLabel();
        lblsinginline = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGİN FORM");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(244, 220, 214));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vektorel/Media/key.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VEKTÖREL BİLİŞİM MÜŞTERİ TAKİP");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SIGN IN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 470));

        jPanel2.setBackground(new java.awt.Color(132, 180, 200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vektorel/Media/icons8-invisible-24.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("User Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 54, -1, -1));

        txtusername.setBackground(new java.awt.Color(132, 180, 200));
        txtusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("User Name");
        txtusername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtusernameMouseClicked(evt);
            }
        });
        jPanel2.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 89, 239, 37));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 160, -1, -1));

        txtpassword.setBackground(new java.awt.Color(132, 180, 200));
        txtpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setText("jPasswordField1");
        txtpassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtpasswordMouseClicked(evt);
            }
        });
        jPanel2.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 195, 239, 38));

        pnlcancel.setBackground(new java.awt.Color(223, 199, 193));
        pnlcancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlcancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlcancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlcancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlcancelMouseExited(evt);
            }
        });
        pnlcancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblcancel.setForeground(new java.awt.Color(132, 180, 200));
        lblcancel.setText("Cancel");
        pnlcancel.add(lblcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblcancelline.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblcancelline.setForeground(new java.awt.Color(255, 255, 255));
        lblcancelline.setText("_______________");
        pnlcancel.add(lblcancelline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jPanel2.add(pnlcancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 392, 100, -1));

        pnlsignin.setBackground(new java.awt.Color(223, 199, 193));
        pnlsignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlsignin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlsigninMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlsigninMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlsigninMouseExited(evt);
            }
        });
        pnlsignin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblsignin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblsignin.setForeground(new java.awt.Color(132, 180, 200));
        lblsignin.setText("Sing In");
        pnlsignin.add(lblsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lblsinginline.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblsinginline.setForeground(new java.awt.Color(255, 255, 255));
        lblsinginline.setText("_______________");
        pnlsignin.add(lblsinginline, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        jPanel2.add(pnlsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 392, 100, -1));

        jLabel6.setText("_____________________________________");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 223, 250, -1));

        jLabel7.setText("_____________________________________");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 116, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 290, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlsigninMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsigninMouseEntered
        lblsinginline.setVisible(true);
        lblsignin.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlsigninMouseEntered

    private void pnlsigninMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsigninMouseExited
        lblsinginline.setVisible(false);
        lblsignin.setForeground(new java.awt.Color(132, 180, 200));
    }//GEN-LAST:event_pnlsigninMouseExited

    private void pnlcancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcancelMouseEntered
        lblcancelline.setVisible(true);
        lblcancel.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_pnlcancelMouseEntered

    private void pnlcancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcancelMouseExited
        lblcancelline.setVisible(false);
        lblcancel.setForeground(new java.awt.Color(132, 180, 200));
    }//GEN-LAST:event_pnlcancelMouseExited

    private void txtusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtusernameMouseClicked
       txtusername.setText("");
    }//GEN-LAST:event_txtusernameMouseClicked

    private void txtpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtpasswordMouseClicked
        txtpassword.setText("");
    }//GEN-LAST:event_txtpasswordMouseClicked

    private void pnlcancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlcancelMouseClicked
       this.dispose();
    }//GEN-LAST:event_pnlcancelMouseClicked

    private void pnlsigninMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlsigninMouseClicked
       String usname = txtusername.getText();
       String passw = txtpassword.getText();
       
            if(usname.equals(StaticValues.userName) 
               && passw.equals(StaticValues.password))
            {
               // frmMainPage frm = new frmMainPage();
               // frm.setVisible(true);
                
                new frmMainPage().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(
                        this, 
                        "Kullanıcı Adı yada Şifre Hatalı",
                        "HATA!!!",
                        JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_pnlsigninMouseClicked

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
      
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
       
        if(durum)
        {
             txtpassword.setEchoChar('*');
             durum=false;
             jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/vektorel/Media/icons8-invisible-24.png"))); // NOI18N
       
        }    
        else{
            txtpassword.setEchoChar((char)0);
            durum=true;
             jLabel8.setIcon(new javax.swing
                     .ImageIcon(getClass()
                             .getResource("/com/vektorel/Media/icons8-eye-24.png"))); // NOI18N
       
        }
        
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcancel;
    private javax.swing.JLabel lblcancelline;
    private javax.swing.JLabel lblsignin;
    private javax.swing.JLabel lblsinginline;
    private javax.swing.JPanel pnlcancel;
    private javax.swing.JPanel pnlsignin;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
